/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-02-21 04:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	Member m = (Member)session.getAttribute("member");
	String[] addr = m.getAddress().split(",");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 정보 보기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1 align=\"center\">");
      out.print( m.getName() );
      out.write("님 정보 보기</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<center>\r\n");
      out.write("<form action=\"/first/mupdate\" method=\"post\">\r\n");
      out.write("<table width=\"600\" cellspacing=\"5\" bgcolor=\"#99ccff\">\r\n");
      out.write("<tr><td width=\"150\">아이디</td>\r\n");
      out.write("<td width=\"450\">\r\n");
      out.write("<input type=\"text\" name=\"userid\" value=\"");
      out.print( m.getId() );
      out.write("\" readonly> </td></tr>\r\n");
      out.write("<tr><td>이 름</td><td>\r\n");
      out.write("<input type=\"text\" name=\"name\" readonly value=\"");
      out.print( m.getName() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>암 호</td>\r\n");
      out.write("<td><input type=\"password\" name=\"userpwd\" id=\"userpwd\" value=\"");
      out.print( m.getPasswd() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>암호확인</td><td>\r\n");
      out.write("<input type=\"password\" name=\"userpwd2\" id=\"userpwd2\" value=\"");
      out.print( m.getPasswd() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>성 별</td>\r\n");
      out.write("\r\n");
 if(m.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("<td><input type=\"radio\" name=\"gender\" value=\"M\" checked> 남\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"F\"> 여</td>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("<td><input type=\"radio\" name=\"gender\" value=\"M\"> 남\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"F\" checked> 여</td>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>나 이</td>\r\n");
      out.write("<td><input type=\"number\" min=\"20\" max=\"100\" name=\"age\" id=\"age\" value=\"");
      out.print( m.getAge() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>이메일</td><td>\r\n");
      out.write("<input type=\"email\" name=\"email\" value=\"");
      out.print( m.getEmail() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>전화번호</td><td>\r\n");
      out.write("<input type=\"tel\" name=\"phone\" value=\"");
      out.print( m.getPhone() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>우편번호</td><td>\r\n");
      out.write("<input type=\"text\" name=\"post\" size=\"10\" value=\"");
      out.print( addr[0] );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>기본주소</td><td>\r\n");
      out.write("<input type=\"text\" name=\"address1\" value=\"");
      out.print( addr[1] );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td>상세주소</td><td>\r\n");
      out.write("<input type=\"text\" name=\"address2\" value=\"");
      out.print( addr[2] );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t<input type=\"submit\" value=\"수정하기\"> &nbsp;\r\n");
      out.write("\t<a href=\"/first/mdelete?userid=");
      out.print( m.getId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t<!-- 쿼리스트링 : 서블릿이름?이름=값&이름=값 -->\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<a href=\"/first/index.jsp\">시작페이지로 이동</a>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
